version: 2

models:
    - name: prices
      description: "A dimension table containing the prices of each contract at each timestamp."
      columns:
        - name: contract_name
          description: "The event being tracked."          
          tests:
            - not_null       
        - name: market_name      
          description: "The event being tracked."
          tests:
            - not_null
        - name: market_id
          description: "The unique identifier for the market."
          tests:
            - not_null
            - relationships:
                to: ref('dim_markets')
                field: market_id
        - name: total_price_change
          description: "The total change in price."
        - name: avg_price_change_percent
          description: "The change in price denoted as percentage."
        - name: record_count 
          description: "The number of records in the table."
        - name: date_id
          description: "Unique ID for date." 
    - name: dim_markets
      description: "A dimension table containing the markets."
      columns:
        - name: market_id
          description: "The unique identifier for the market."
          tests:
            - not_null
        - name: market_name
          description: "The event being tracked."
          tests:
            - not_null
        
