version: 2

models:
    - name: prices
      description: "A dimension table containing the prices of each contract at each timestamp."
      columns:
        - name: contract_id
          description: "The unique identifier for the contract."
          tests:
            - not_null       
        - name: market_name      
          description: "The event being tracked."
          tests:
            - not_null
        - name: market_id
          description: "The unique identifier for the market."
          tests:
            - not_null
            - relationships:
                to: ref('dim_markets')
                field: market_id
        - name: price_change
          description: "The change in price."
        - name: price_change_percent
          description: "The change in price denoted as percentage."
    - name: dim_markets
      description: "A dimension table containing the markets."
      columns:
        - name: market_id
          description: "The unique identifier for the market."
          tests:
            - not_null
        - name: market_name
          description: "The event being tracked."
          tests:
            - not_null
        
